### PR TITLE
Vcpkg port

### PR DESCRIPTION
**Pull request by grisumbras**
As promised, a vcpkg port that allows consuming Scope as vcpkg package.

### CODE REVIEW

**Comment by Lastique** [comment]
Could you add a license header comment?

Do I understand correctly that the hash sums will require updating whenever new commits are made?

**Comment by Lastique** [comment]
Also, Boost.Scope requires Boost 1.84 (i.e. the current master or develop).

**Comment by grisumbras** [comment]
> Could you add a license header comment?

Will do.

> Do I understand correctly that the hash sums will require updating whenever new commits are made?

Yes. Normally vcpkg ports aren't parts of the packaged project, but are parts of a separate "repository" project.

**Comment by Lastique** [comment]
> > Do I understand correctly that the hash sums will require updating whenever new commits are made?
> 
> Yes. Normally vcpkg ports aren't parts of the packaged project, but are parts of a separate "repository" project.

In that case I won't be able to maintain it. It would be ok to keep it for the sake of the review (provided that the 1.84 requirement can be managed), but after that I will probably remove it. If the library is accepted, that shouldn't be a problem, as the library would be packaged as part of Boost.

**Comment by grisumbras** [comment]
Yes, the intention is for this to be temporary, because vcpkg team makes Boost packages for vcpkg by themselves.

**Comment by Lastique** [comment]
Thanks.

**Pull request merged**
