### PR TITLE
Added Conan recipe

### PR DESCRIPTION
**Pull request by grisumbras**
As promised, here's a simple Conan package recipe that allows consuming Scope as a Conan package

### CODE REVIEW

**Comment by Lastique** [comment]
Could you add a license header comment?

**Comment by Lastique** [comment]
Also, Boost.Scope requires Boost 1.84 (i.e. the current master or develop).

**Comment by grisumbras** [comment]
> Also, Boost.Scope requires Boost 1.84 (i.e. the current master or develop).

That's going to be a problem: none of the package managers will have Boost 1.84 packages by the time of Scope review.

**Comment by Lastique** [comment]
> > Also, Boost.Scope requires Boost 1.84 (i.e. the current master or develop).
> 
> That's going to be a problem: none of the package managers will have Boost 1.84 packages by the time of Scope review.

If Conan and vcpkg support patches, you could add a patch that switches from `boost::core::invoke_swap` back to `boost::swap`. This will make the library compatible with 1.83. This is what I had to do for godbolt version, too.

**Comment by Lastique** [comment]
Here's the patch:

[1.83_compat.patch.gz](https://github.com/Lastique/scope/files/13231313/1.83_compat.patch.gz)

**Comment by grisumbras** [comment]
They do support patches. I'll update the PRs.

**Comment by Lastique** [comment]
Thanks.

**Pull request merged**
